### PR TITLE
[Readme] Consistently present Meshery logo

### LINKED ISSUE #224: [Readme] Consistently present Meshery logo
**Current Situation**
A brief description of what the current circumstance is.

As you see the current logo is quite big and is not consistent. 
**Desired Situation**
A brief description of the necessary action to take.

Make it consistent with github.com/meshery/meshery 's readme logo.

---
**Contributor Resources**
- 📝 [Meshery Adapters Spreadsheet](https://docs.google.com/spreadsheets/d/1rGGpSXC68iDJzNRU-qZIRQsZUwkt1qLFg7JCs4pfvbU/edit?usp=sharing)
- [Meshery documentation site](https://docs.meshery.io/)
- [Meshery documentation source](https://github.com/meshery/meshery/tree/master/docs)
- [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

### PR DESCRIPTION
**Pull request by XDRAGON2002**
Signed-off-by: Anant Vijay <anantvijay3@gmail.com>

**Description**
image

This PR fixes #224 

**Notes for Reviewers**
Updated README.md with the proper logo to be used

**[Signed commits](../CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin)**
- [x] Yes, I signed my commits.

### CODE REVIEW

**Comment by leecalcote** [comment]
@npdebs, you might want to review this.

**Comment by NPDebs** [comment]
> @npdebs, you might want to review this.

Ah yes, thank you, Mr @leecalcote . Let me grab my glasses. 🔎🧐

**Review by NPDebs — CHANGES_REQUESTED** [review]
This looks good in general. Just a few things that need attention...

Make a copy of the images in this repo (under img/readme), and then use a relative path to apply the changes.

**Comment by XDRAGON2002** [comment]
@NPDebs made the required changes.

**Comment by NPDebs** [comment]
> @NPDebs made the required changes.

Awesome! Looking good. 🙌🏼

Just one last change and we're good to go. 👍🏻

**Comment by XDRAGON2002** [comment]
> > @NPDebs made the required changes.
> 
> Awesome! Looking good. 🙌🏼
> 
> Just one last change and we're good to go. 👍🏻

Could you specify what more changes are required?

**Comment by NPDebs** [comment]
> > > @NPDebs made the required changes.
> > 
> > Awesome! Looking good. 🙌🏼
> > 
> > Just one last change and we're good to go. 👍🏻
> 
> Could you specify what more changes are required?

Pardon me, please. I'd specified the change to be made within the commit. 

Please, use the Meshery logo without a tagline.

**Comment by XDRAGON2002** [comment]
@NPDebs made the required changes.

**Review by NPDebs — APPROVED** [review]
LGTM! 🚀
Great job. Thank you, @XDRAGON2002 💯💪🏼

**Review by adithyaakrishna — APPROVED** [review]
LGTM

**Comment by adithyaakrishna** [comment]
@Revolyssup Could you please merge this PR? Thanks in advance :)

**Comment by NPDebs** [comment]
👀

**Review by alphaX86 — APPROVED** [review]
LGTM. Seems a maintainer needs to merge this one 🙃

**Review by acald-creator — APPROVED** [review]

**Pull request merged**
